<?php
return [
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response',
    'entity'  => 'OptionGroup',
    'cleanup' => 'never',
    'params'  => [
      'version'   => 3,
      'name'      => 'hlr_lookup_response',
      'title'     => 'HLR Lookup Response',
      'data_type' => 'Integer',
      'is_active' => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_success',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 100,
      'name'            => 'success',
      'label'           => 'success',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_temporary_error',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 102,
      'name'            => 'temporary_error',
      'label'           => 'temporary error',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_unknown_subscriber',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 103,
      'name'            => 'unknown_subscriber',
      'label'           => 'unknown subscriber',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_teleservice_not_provisioned',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 104,
      'name'            => 'teleservice_not_provisioned',
      'label'           => 'teleservice not provisioned',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_call_barred',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 105,
      'name'            => 'call_barred',
      'label'           => 'call barred',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_facility_not_supported',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 107,
      'name'            => 'facility_not_supported',
      'label'           => 'facility not supported',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_system_failure',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 108,
      'name'            => 'system_failure',
      'label'           => 'system failure',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_absent_subscriber',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 109,
      'name'            => 'absent_subscriber',
      'label'           => 'absent subscriber',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_unexpected_data_value',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 111,
      'name'            => 'unexpected_data_value',
      'label'           => 'unexpected data value',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_service_unreachable',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 112,
      'name'            => 'service_unreachable',
      'label'           => 'service unreachable',
      'is_active'       => 1,
    ],
  ],
  [
    'module'  => 'hlrlookup',
    'name'    => 'hlr_lookup_response_msisdn_wrong',
    'entity'  => 'OptionValue',
    'cleanup' => 'never',
    'params'  => [
      'version'         => 3,
      'option_group_id' => 'hlr_lookup_response',
      'value'           => 921,
      'name'            => 'msisdn_wrong',
      'label'           => 'msisdn wrong',
      'is_active'       => 1,
    ],
  ],
];
