<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from hlrlookup/xml/schema/CRM/Hlrlookup/HlrLookupHistory.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:a302bd6e91e46a5f1933257c21c1ac63)
 */
use CRM_Hlrlookup_ExtensionUtil as E;

/**
 * Database access object for the HlrLookupHistory entity.
 */
class CRM_Hlrlookup_DAO_HlrLookupHistory extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_hlr_lookup_history';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique HlrLookupHistory ID
   *
   * @var int
   */
  public $id;

  /**
   * Phone number stripped of all whitespace, letters, and punctuation.
   *
   * @var string
   */
  public $msisdn;

  /**
   * Which Mobile Provider does this phone belong to.
   *
   * @var int
   */
  public $mobile_provider_id;

  /**
   * @var int
   */
  public $response_code_id;

  /**
   * Date of the Response
   *
   * @var datetime
   */
  public $response_date;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_hlr_lookup_history';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Hlr Lookup Histories') : E::ts('Hlr Lookup History');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique HlrLookupHistory ID'),
          'required' => TRUE,
          'where' => 'civicrm_hlr_lookup_history.id',
          'table_name' => 'civicrm_hlr_lookup_history',
          'entity' => 'HlrLookupHistory',
          'bao' => 'CRM_Hlrlookup_DAO_HlrLookupHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'msisdn' => [
          'name' => 'msisdn',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Msisdn'),
          'description' => E::ts('Phone number stripped of all whitespace, letters, and punctuation.'),
          'required' => TRUE,
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'where' => 'civicrm_hlr_lookup_history.msisdn',
          'table_name' => 'civicrm_hlr_lookup_history',
          'entity' => 'HlrLookupHistory',
          'bao' => 'CRM_Hlrlookup_DAO_HlrLookupHistory',
          'localizable' => 0,
          'html' => [
            'label' => E::ts("Numeric"),
          ],
          'add' => NULL,
        ],
        'mobile_provider_id' => [
          'name' => 'mobile_provider_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Mobile Provider'),
          'description' => E::ts('Which Mobile Provider does this phone belong to.'),
          'required' => TRUE,
          'where' => 'civicrm_hlr_lookup_history.mobile_provider_id',
          'table_name' => 'civicrm_hlr_lookup_history',
          'entity' => 'HlrLookupHistory',
          'bao' => 'CRM_Hlrlookup_DAO_HlrLookupHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'mobile_provider',
            'optionEditPath' => 'civicrm/admin/options/mobile_provider',
          ],
          'add' => NULL,
        ],
        'response_code_id' => [
          'name' => 'response_code_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('HLR lookup response code'),
          'required' => TRUE,
          'where' => 'civicrm_hlr_lookup_history.response_code_id',
          'table_name' => 'civicrm_hlr_lookup_history',
          'entity' => 'HlrLookupHistory',
          'bao' => 'CRM_Hlrlookup_DAO_HlrLookupHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'hlr_lookup_response',
            'optionEditPath' => 'civicrm/admin/options/hlr_lookup_response',
          ],
          'add' => NULL,
        ],
        'response_date' => [
          'name' => 'response_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Response Date'),
          'description' => E::ts('Date of the Response'),
          'required' => TRUE,
          'where' => 'civicrm_hlr_lookup_history.response_date',
          'table_name' => 'civicrm_hlr_lookup_history',
          'entity' => 'HlrLookupHistory',
          'bao' => 'CRM_Hlrlookup_DAO_HlrLookupHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'hlr_lookup_history', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'hlr_lookup_history', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_msisdn' => [
        'name' => 'index_msisdn',
        'field' => [
          0 => 'msisdn',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hlr_lookup_history::0::msisdn',
      ],
      'index_response_date' => [
        'name' => 'index_response_date',
        'field' => [
          0 => 'response_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hlr_lookup_history::0::response_date',
      ],
      'index_msisdn_response_date' => [
        'name' => 'index_msisdn_response_date',
        'field' => [
          0 => 'msisdn',
          1 => 'response_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_hlr_lookup_history::0::msisdn::response_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
